---
# tasks file for gcsfuse
- name: Add GCSfuse repository into sources list
  block:
    - name: Gcsfuse repo key | no apt key
      ansible.builtin.get_url:
        url: "{{ gcsfuse_repo_key_url }}"
        dest: "{{ _gcsfuse_repo_path_gpg_key }}"
        mode: "0644"

    - name: Install gcsfuse repo
      ansible.builtin.apt_repository:
        repo: "deb {{ gcsfuse_repo_url }}"
        filename: "{{ _gcsfuse_repo_filename }}"
        state: present

- name: Install fuse and gcsfuse
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - "fuse"
    - "gcsfuse"
