---
- name: Mount GCS Fuse
  ansible.posix.mount:
    src: "{{ item.bucket }}"
    path: "{{ item.mount_point }}"
    opts: >-
      rw,x-systemd.requires=network-online.target,user,
      key-file={{ item.gcp_keyfile }}
    fstype: gcsfuse
    state: mounted
  loop: gcsfuse_mounts
