- name: Remove GCSfuse repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb {{ gcsfuse_repo_url }}"
    state: absent
    filename: gcsfuse

- name: Remove an Apt signing key, will not download if present
  ansible.builtin.file:
    path: "{{ _gcsfuse_repo_path_gpg_key }}"
    state: absent
