- name: Unmount GCS Fuse
  ansible.posix.mount:
    src: "{{ item.bucket }}"
    path: "{{ item.mount_point }}"
    opts: >-
      rw,x-systemd.requires=network-online.target,user,key_file={{ item.gcp_keyfile }}
    fstype: gcsfuse
    state: absent
  loop: "{{ gcsfuse_mounts }}"

- name: Uninstall gcsfuse
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - "gcsfuse"

- name: Remove GCSfuse repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb {{ gcsfuse_repo_url }}"
    state: absent
    filename: gcsfuse

- name: Remove an Apt signing key, will not download if present
  ansible.builtin.file:
    path: "{{ _gcsfuse_repo_path_gpg_key }}"
    state: absent
